backend: local
backup_directory: /Users/larra/INGInious/backup
local-config: {}
mongo_opt:
    database: INGInious
    host: db
plugins: []
superadmins:
- superadmin
tasks_directory: /Users/larra/INGInious/tasks
use_minified_js: false
plugins:
    - plugin_module: inginious.frontend.webapp.plugins.statistics
    - plugin_module: inginious.frontend.webapp.plugins.task_cache
